const tricks = [
  { name: "Ollie",           diff: [1, 1, 2, 2] },
  { name: "Frontside 180",             diff: [1, 1, 2, 2] },
  { name: "Backside 180",   diff: [1, 1, 2, 2] },
  { name: "Pop Shuvit",             diff: [1, 1, 2, 2] },
  { name: "Frontside Pop Shuvit",   diff: [1, 1, 2, 2] },
  { name: "Kickflip",        diff: [1, 2, 3, 3] },
  { name: "Heelflip",        diff: [1, 2, 3, 3] },
  { name: "Treflip",         diff: [2, 2, 3, 3] },
  { name: "Varial Flip",     diff: [2, 2, 3, 3] },
  { name: "Varial Heelflip", diff: [2, 2, 3, 3] },
  { name: "Hardflip",        diff: [3, 3, 3, 3] },
  { name: "Inward Heel",     diff: [3, 3, 3, 3] },
    { name: "Frontside Kickflip",        diff: [3, 3, 3, 3] },
  { name: "Frontside Heelflip",     diff: [3, 3, 3, 3] },
  { name: "Backside Kickflip",        diff: [3, 3, 3, 3] },
  { name: "Backside Heelflip",     diff: [3, 3, 3, 3] },
  { name: "Bigspin Kickflip",     diff: [3, 3, 3, 3] },
  { name: "Bigspin",     diff: [3, 1, 3, 2] },
    { name: "Frontside Bigspin",     diff: [3, 3, 3, 3] },
  { name: "Frontside Bigflip",     diff: [3, 3, 3, 3] },
  { name: "Bigspin Heelflip",     diff: [3, 3, 3, 3] },
  { name: "Frontside Bigspin Heelflip",     diff: [3, 3, 3, 3] },
  { name: "Lazer Flip",     diff: [4, 4, 4, 4] },

];
